require 'colored'
require_relative 'tictactoe/cell'
require_relative 'tictactoe/board'
require_relative 'tictactoe/abstract_player'
require_relative 'tictactoe/computer_player'
require_relative 'tictactoe/game_interactor'
require_relative 'console_player'
require_relative 'game_presenter'